#!/usr/bin/env bash
# Fix the Apache server and serve the "Hello Holberton" page

# Update package list and install apache2
sudo apt-get update
sudo apt-get install -y apache2

# Create the "Hello Holberton" page
echo "Hello Holberton" | sudo tee /var/www/html/index.html > /dev/null

# Start Apache
sudo service apache2 start
